// AUTO-GENERATED by scripts/gen-manifest.mjs — DO NOT EDIT BY HAND.
// Templated from deployments/arbitrum-sepolia.json (uniswap.nonfungiblePositionManager),
// the SINGLE address registry. Regenerated by `pnpm prepare:manifest`; committed so
// codegen/build run offline. This is the AssemblyScript twin of the SDK's addresses.ts.
import { Address } from '@graphprotocol/graph-ts'

/** The NonfungiblePositionManager the protocol is wired to (positions() custody NFT). */
export const NPM_ADDRESS = Address.fromString('0x6b2937bde17889edcf8fbd8de31c3c2a70bc4d65')
